export enum RolePermissionValidationConstant {
  IS_ROLE_ID_EMPTY = 'IS_ROLE_ID_EMPTY',
  IS_ROLE_ID_NUMBER = 'IS_ROLE_ID_NUMBER',
  IS_PERMISSION_ID_EMPTY = 'IS_PERMISSION_ID_EMPTY',
  IS_PERMISSION_ID_NUMBER = 'IS_PERMISSION_ID_NUMBER',
}
