export enum UserValidationConstant {
  IS_EMAIL_INVALID = 'IS_EMAIL_INVALID',
  IS_EMAIL_EMPTY = 'IS_EMAIL_EMPTY',
  IS_PASSWORD_EMPTY = 'IS_PASSWORD_EMPTY',
  IS_PASSWORD_STRING = 'IS_PASSWORD_STRING',
  PASSWORD_POLICY_ENFORCEMENT = 'PASSWORD_POLICY_ENFORCEMENT',
  IS_TOKEN_STRING = 'IS_TOKEN_STRING',
  IS_TOKEN_EMPTY = 'IS_TOKEN_EMPTY',
  IS_OTP_STRING = 'IS_OTP_STRING',
  IS_OTP_EMPTY = 'IS_OTP_EMPTY',
}
