version: '3'
services:
  boilerplate-be:
    image: node:20
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    command: npm run start
    ports:
      - ${NODE_HOST_PORT}:${NODE_CONTAINER_PORT}
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://${DOCKER_DATABASE_USERNAME}:${DOCKER_DATABASE_PASSWORD}@postgres:5432/${DOCKER_DATABASE_NAME}
      REDIS_URL: redis://redis:${REDIS_CONTAINER_PORT}/0
      NODE_HOST_PORT: ${NODE_HOST_PORT}
      NODE_CONTAINER_PORT: ${NODE_CONTAINER_PORT}
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DOCKER_DATABASE_NAME}
      POSTGRES_USER: ${DOCKER_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
      POSTGRES_HOST_PORT: ${POSTGRES_HOST_PORT}
      POSTGRES_CONTAINER_PORT: ${POSTGRES_CONTAINER_PORT}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.10
    restart: always
    container_name: redis_cache
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}
    environment:
      REDIS_HOST_PORT: ${REDIS_HOST_PORT}
      REDIS_CONTAINER_PORT: ${REDIS_CONTAINER_PORT}
volumes:
  postgres_data:
