version: '2'
services:
  base:
    image: node:18
    volumes:
      - .:/usr/src/
    working_dir: /usr/src/
  install:
    extends:
      service: base
    command: npm i
  build:
    extends:
      service: base
    command: npm run build
  seed:
    extends:
      service: base
    command: npm run seed
  migration:
    extends:
      service: base
    command: npm run migration:run
